[package]
name = "wparse"
version = "0.1.0"
authors = ["Loïc Grobol <loic.grobol@inria.fr>"]
edition = "2018"

[dependencies]
bzip2 = "0.3.3"
parse_wiki_text = "0.1.5"
parse_mediawiki_dump = "0.1.0"
regex = "1.3.7"
lazy_static = "1.4.0"
rayon = "1.3"
